"""Initial migration.

Revision ID: 91743d10e287
Revises: 
Create Date: 2022-12-16 22:48:48.989865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91743d10e287'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('name', sa.String(length=225), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('titles',
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('piece_id', sa.Integer(), nullable=False, foreign_keys='Piece.id'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('versions',
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('storage_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=225), nullable=False),
    sa.Column('upload_name', sa.String(length=225), nullable=False),
    sa.Column('mimetype', sa.String(length=225), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('piece_id', sa.Integer(), nullable=False, foreign_keys='Piece.id'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pieces',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('info', sa.Text(), nullable=False),
    sa.Column('info_updated', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('selected_title_id', sa.Integer(), nullable=True),
    sa.Column('selected_version_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['selected_title_id'], ['titles.id'], ),
    sa.ForeignKeyConstraint(['selected_version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_groups',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('pieces_groups',
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('piece_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['piece_id'], ['pieces.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pieces_groups')
    op.drop_table('users_groups')
    op.drop_table('pieces')
    op.drop_table('versions')
    op.drop_table('users')
    op.drop_table('titles')
    op.drop_table('groups')
    # ### end Alembic commands ###
